name: Test Pipeline

on:
  push:
    branches: [ master   ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          # We use the standard filename 'docker-compose.yml' 
          # based on your first message.
          docker compose -f docker-compose-test.yml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from web

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-test.yml down --volumes